import pandas

# -*- coding: utf-8 -*-
"""CB_share.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tJSknzyRL5b8CpD_-7vw1VASoHkbQ1Wc
"""

# 1028 효정님께 전달

######파일 읽어오는 거 디렉토리 바꿔서 사용##############
#item_matrix 불러오기p
item_matrix = pandas.read_csv('C:/Users/x_xih/teamProject/finalHouse/final_house/server/preprocessed_datagu_test1.csv', index_col=0)

#user_info 불러오기: 사용자 설문 기본정보(연령, 취미 등)
user_info = pandas.read_csv('C:/Users/x_xih/teamProject/finalHouse/final_house/server/preprocessed_datauser_info_test_1.csv', index_col=0)


# #user_preference_info 불러오기: 사용자가 지정한 우선순위 정보(온라인 설문의 1번 질문)
# user_pre_info = = pandas.read_csv('/content/drive/MyDrive/2023_아미공_졸업프로젝트/03_데이터/preprocessed_datauser_info_test_1.csv', index_col=0)
# user_pre_info






#######################
#user_matrix 불러오기 (test, 가중치 계산 자동화 과정 누락)
user_matrix = pandas.read_csv('C:/Users/x_xih/teamProject/finalHouse/final_house/server/user_matrix_test1.csv', index_col=0)
user_matrix

#마지막 행의 유저만 추출해서 matrix
last_user = user_matrix.iloc[-1:]
last_user

#user-item matrix 계산
user_item_matrix = last_user.dot(item_matrix)
user_item_matrix

#user_item_matrix 계산하기
#가장 마지막 행의 사용자에 대해
last_user_score = user_item_matrix
results = last_user_score.max().nlargest(3).index

results


#추천결과를 user_info에 업데이트하기
user_info.loc[user_info.index[-1], '결과'] = ', '.join(results)
user_info

#추천 결과 update한 것을 user_info를 파일에 저장(로컬 파일에 덮어쓰기)
################### 효정님 directory_path를 효정님이 파일 저장하신 디렉토리로 바꿔서 사용해주세요 ########################


# directory_path = 'C:\Users\x_xih\teamProject\finalHouse\final_house\server\preprocessed_datauser_info_test_1.csv'
# file_name = 'user_info_test_1.csv'  # 저장할 파일 이름을 지정

# user_info_test1.to_csv(directory_path + file_name, index=True)

user_info_test1.to_csv('C:/Users/x_xih/teamProject/finalHouse/final_house/server/preprocessed_datauser_info_test_1.csv', index=True)
